// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharpMember.Core.Data.DbContexts;

#nullable disable

namespace SharpMember.Migrations.Postgres.Migrations.Member
{
    [DbContext(typeof(MemberContext))]
    partial class MemberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Member")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemberProfileItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("MemberProfileItemTemplates", "Member");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Announcement")
                        .HasColumnType("text");

                    b.Property<string>("Introduction")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Communities", "Member");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Groups", "Member");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.GroupMemberRelation", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupRole")
                        .HasColumnType("text");

                    b.HasKey("MemberId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMemberRelation", "Member");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<string>("CommunityRole")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MemberNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<bool>("Renewed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Members", "Member");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.MemberProfileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemValue")
                        .HasColumnType("text");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberProfileItemTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberProfileItemTemplateId");

                    b.ToTable("MemberProfileItems", "Member");
                });

            modelBuilder.Entity("MemberProfileItemTemplate", b =>
                {
                    b.HasOne("SharpMember.Core.Data.Models.MemberSystem.Community", "Community")
                        .WithMany("MemberProfileItemTemplates")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Group", b =>
                {
                    b.HasOne("SharpMember.Core.Data.Models.MemberSystem.Community", "Community")
                        .WithMany("Groups")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.GroupMemberRelation", b =>
                {
                    b.HasOne("SharpMember.Core.Data.Models.MemberSystem.Group", "Group")
                        .WithMany("GroupMemberRelations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMember.Core.Data.Models.MemberSystem.Member", "Member")
                        .WithMany("GroupMemberRelations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Member", b =>
                {
                    b.HasOne("SharpMember.Core.Data.Models.MemberSystem.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.MemberProfileItem", b =>
                {
                    b.HasOne("SharpMember.Core.Data.Models.MemberSystem.Member", "Member")
                        .WithMany("MemberProfileItems")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemberProfileItemTemplate", "MemberProfileItemTemplate")
                        .WithMany()
                        .HasForeignKey("MemberProfileItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MemberProfileItemTemplate");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Community", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("MemberProfileItemTemplates");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Group", b =>
                {
                    b.Navigation("GroupMemberRelations");
                });

            modelBuilder.Entity("SharpMember.Core.Data.Models.MemberSystem.Member", b =>
                {
                    b.Navigation("GroupMemberRelations");

                    b.Navigation("MemberProfileItems");
                });
#pragma warning restore 612, 618
        }
    }
}
