name: Test Python and F# Scripts

on:
  push:
    branches:
      - master

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up .NET SDK (v8.0.x for F#)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Python Script
        run: |
          python3 BuildTools/test2.py

      - name: Run F# Script
        run: |
          dotnet fsi BuildTools/test1.fsx
